    # /etc/nginx/conf.d/default.conf
    server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip base (facoltativo ma utile)
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # File statici con cache aggressiva
    # location ~* \.(?:css|js|mjs|png|jpg|jpeg|gif|svg|ico|webp|woff2?)$ {
    #     expires 30d;
    #     add_header Cache-Control "public, max-age=2592000, immutable";
    #     try_files $uri =404;
    # }
    location /agent/ {
        proxy_pass http://localhost:5000/;
    }

    # Fallback SPA (se usi router client-side)
    # location / {
    #    try_files $uri $uri/ /index.html;
    # }

    # Sicurezza base
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header Referrer-Policy "no-referrer-when-downgrade";
}
